import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import { jetbrains_mono, lato, montserrat } from "@/utils/fonts";
import StairTransition from "@/components/layout/StairTransition";
import PageTransition from "@/components/layout/PageTransition";
import SidebarButton from "@/components/sidebar/SidebarButton";
import Sidebar from "@/components/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Nazri Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${montserrat.variable} ${jetbrains_mono.variable} bg-background`}
      >
        {/* <Header /> */}
        <StairTransition />

        <PageTransition>
          <Sidebar></Sidebar>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
